name: CI - SMS Spam RNN

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 pytest torch numpy optuna
        
      - name: Run format
        run: make format
      
      - name: Run linter
        run: make lint

      - name: Run Optuna tuning
        run: make tune

      - name: Retrain final model
        run: make train_final

      - name: Build Docker image
        run: make docker-build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

      - name: Docker login to ECR
        run: make docker-login
        
      - name: Build, tag, push Docker image
        run: make docker-all
 
      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: |
            final_best_model.pth
            best_params.json
